language: php
php:
    - 7.2
    - 7.3
    - nightly
before_script: composer install --prefer-source
script: vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
    - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" = "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
